name: transfg-mps
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch::pytorch=2.1.2
  - pytorch::torchvision=0.16.2
  - pytorch::torchaudio=2.1.2
  - pip:
      - -r requirements.txt
